[workspace]

[package]
name = "tizen-ui-app-tokio"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
publish = false

[dependencies]
tizen = { git = "https://github.com/smohantty/rust-tizen.git", features = ["app-tokio"] }
log = "0.4"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "time"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
