[package]
name = "tizen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Idiomatic Rust bindings to Tizen platform APIs (umbrella crate)"
categories = ["api-bindings", "os::unix-apis"]
keywords = ["tizen", "platform", "bindings", "ffi"]
readme = "README.md"

[features]
default = []
dlog = ["dep:tizen-dlog"]
app = ["dep:tizen-app"]
app-tokio = ["app", "tizen-app/tokio"]
input = ["dep:tizen-input"]
screenshot = ["dep:tizen-screenshot"]
window = ["dep:tizen-window"]
egl = ["window", "dep:tizen-egl"]
eframe = ["egl", "dep:tizen-eframe"]

[dependencies]
tizen-dlog = { workspace = true, optional = true }
tizen-app = { workspace = true, optional = true }
tizen-input = { workspace = true, optional = true }
tizen-screenshot = { workspace = true, optional = true }
tizen-window = { workspace = true, optional = true }
tizen-egl = { workspace = true, optional = true }
tizen-eframe = { workspace = true, optional = true }

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
